name: geo_rastreo
description: AplicaciÃ³n con login
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  socket_io_client: ^2.0.3+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/backgrounds/
    - assets/images/icons/